name: Verify changes with cifuzzer
run-name: ${{ github.actor }} is fuzzing this shit
on: [push, pull_request]
jobs:
  fuzz:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: build image
        run: ./build.sh
      - name: run container
        run: docker run cifuzz-docker-image
